### ISSUE TITLE
incompatibility with slot extender

### ISSUE THREAD

**Issue by LuisMiguelGomezNavas** [silvervirus/PrimeSonicBepinex_Smlhelper_update#2]
when i use the mod more cyclops upgrades with slot extender in some slots the upgrades disappear and when i open again the upgrade console the upgrades are there but i can´t take out or move to another slot

**Comment by silvervirus** [comment]
I think I might know what's wrong with that

**Comment by silvervirus** [comment]
Nope what I did what I can do and that didn't help

**Comment by silvervirus** [comment]
so i released an update in mod beta in the modding server

**Comment by silvervirus** [comment]
Returned back to normal 
[MoreCyclopsUpgrades.zip](https://github.com/silvervirus/PrimeSonicBepinex_Smlhelper_update/files/12210355/MoreCyclopsUpgrades.zip)
SlotExtender with out the cyclops slots included
[SlotExtender(nocyclops).zip](https://github.com/silvervirus/PrimeSonicBepinex_Smlhelper_update/files/12210356/SlotExtender.nocyclops.zip)
